In [1]:
import numpy as np   
X=np.array([2,3,4,5]).T
degree=2
n = len(X)

# add 1s column
X_ = np.c_[np.ones([n, 1]), X]
for  i in range(2,degree+1):
    X_ = np.c_[X_, np.power(X,i)]

n, d = X_.shape

In [2]:
X_

array([[1., 2., 4.],
       [1., 2., 4.],
       [1., 2., 4.],
       [1., 2., 4.]])

In [8]:
a =np.copy(X[0:2])

In [9]:
a

array([2, 3])

In [11]:
a= np.power((X-1),2).sum();

In [12]:
a

30

In [5]:
 X_ = np.copy(X)
for  i in range(2,d+1):
    X_ = np.c_[X_, np.power(X,i)]
print(X_)
print(d)

[[  2   4   8]
 [  3   9  27]
 [  4  16  64]
 [  5  25 125]]
3
